<?php

use Illuminate\Database\Seeder;
use App\Models\Keyword;
use App\Models\User;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $mainSuperUserId = User::where([
            'email' => 'fulladmin@goodwork.io'
        ])->get()->first()->id;
        $this->insertKeywords($mainSuperUserId);
    }

    private function insertKeywords($mainSuperUserId)
    {
        $keywords = $this->keywordData();
        foreach ($keywords as $key => $value) {
            foreach($value as $item){
                factory(Keyword::class)->create([
                    'created_by' => $mainSuperUserId,
                    'filter' => $key,
                    'title' => $item,
                ]);
            }
        }
    }

    private function keywordData()
    {
        return [
            'AssignmentDuration' => [
                '4 Week',
                '6 Week',
                '8 Week',
                '10 Week',
                '12 Week',
                '18 Week',
                '24 Week',
                '26 Week'
            ],
            'FacilityType' => [
                'Acute Care Hospital',
                'Behavioral Health Hospital',
                'Ambulatory Care Facility (includes surgery centers, free-standing emergency rooms, and clinics)',
                'Assisted Living',
                'Skilled Nursing',
                'Other'
            ],
            'LeadershipRoles' => [
                'Charge Worker or Clinical Worker Coordinator',
                'Supervisor',
                'Manager',
                'Director',
                'Assistant Chief Nursing Officer (ACNO)',
                'Chief Nursing Officer (CNO)'
            ],
            'NursingDegree' => [
                'Associate\'s or ADN',
                'Bachelor\'s or BSN',
                'Master\'s or MSN',
                'Doctorate\'s or DNP'
            ],
            'Speciality' => [
                'Emergency Room',
                'Medical / Surgical / Telemetry',
                'Critical Care (Adult ICU, Cardiovascular ICU, Intermediate ICU)',
                'Operating Room',
                'PACU / Recovery',
                'Cath Lab / Interventional Radiology',
                'Labor & Delivery',
                'Mother-Baby',
                'Neonatal ICU',
                'Pediatrics / Pediatrics ICU',
                'Case Management (non-bedside)',
                'Infection Prevention (non-bedside)'
            ],
            'GeographicPreference' => [
                'Local Traveler (within 25 miles)',
                'Regional Traveler (within 100 miles)',
                'National Traveler (anywhere in the US)',
                'International Traveler (anywhere in North America or Europe)'
            ],
            'Certification' => [
                'Advanced HIV/AIDS Certified Registered Worker (AACRN)',
                'Advanced Traumatic Life Support (ATLS)',
                'Advanced Cardiac Life Support (ACLS) ',
                'Basic Life Support (BLS)',
                'Clinical Worker Specialist; Wellness through Acute Care (Adult-Gerontology) (ACCNS-AG)',
                'Clinical Worker Specialist; Wellness through Acute Care (Neonatal) (ACCNS-N)',
                'Clinical Worker Specialist, Wellness through Acute Care (Pediatric) (ACCNS-P)',
                'Advanced Certified Hospice and Palliative Worker (ACHPN)',
                'Acute Care Worker Practitioner (ACNP-BC)',
                'Acute Care Worker Practitioner (Adult-Gerontology) (ACNPC-AG)',
                'Adult Health Clinical Worker Specialist (ACNS-BC)',
                'HIV/AIDS Certified Registered Worker (ACRN)',
                'Advanced Diabetes Management (specialty certification, retired exam) (ADM-BC)',
                'Advanced Diabetes Management (ADM-BC)',
                'Certified Asthma Educator (AE-C)',
                'Forensic Nursing, Advanced (AFN-BC)',
                'Advanced Forensic Nursing (AFN-BC)',
                'Adult-Gerontology Acute Care Worker Practitioner (AGACNP-BC)',
                'Adult-Gerontology Clinical Worker Specialist (AGCNS-BC)',
                'Genetics Nursing, Advanced (AGN-BC)',
                'Adult-Gerontology Primary Care Worker Practitioner (AGPCNP-BC)',
                'Advanced Holistic Worker, Board Certified (AHN-BC)',
                'Adult Worker Practitioner (ANP-BC)',
                'Acute Care Worker Practitioner (Adult) (ACNPC)',
                'Advanced Oncology Certified Worker (AOCN)',
                'Advanced Oncology Certified Worker Practitioner (AOCNP)',
                'Advanced Oncology Certified Clinical Worker Specialist (AOCNS)',
                'Advanced Practice Holistic Worker (APHN-BC)',
                'Board Certified-Advanced Diabetes Management (BC-ADM)',
                'Blood & Marrow Transplant Certified Worker (BMTCN)',
                'Electronic Fetal Monitoring (C-EFM)',
                'Neonatal Pediatric Transport (C-NPT)',
                'Certified Aesthetic Worker Specialist (CANS)',
                'Certified Ambulatory Perianesthesia Worker (CAPA)',
                'Certified Addictions Registered Worker (CARN)',
                'Certified Addictions Registered Worker - Advanced Practice (CARN-AP)',
                'Certified Breast Care Worker (CBCN)',
                'Correctional Behavioral Health Certification (CBHC)',
                'Certified Continence Care Worker (CCCN)',
                'Certified Continence Care Worker-Advanced Practice (CCCN-AP)',
                'Certified Correctional Health Professional-Advanced (CCHP-A)',
                'Certified Correctional Health Professional-RN (CCHP-RN)',
                'Certified Clinical Hemodialysis Technician (CCHT)',
                'Certified Clinical Hemodialysis Technician-Advanced (CCHTA)',
                'Acute/Critical Care Clinical Worker Specialist (Adult, Pediatric & Neonatal) (CCNS)',
                'Certified Clinical Research Associate (CCRA)',
                'Certified Clinical Research Coordinator (CCRC)',
                'Acute/Critical Care Nursing (Adult, Pediatric & Neonatal) (CCRN)',
                'Tele-ICU Acute/Critical Care Nursing (Adult) (CCRN-E)',
                'Acute/Critical Care Knowledge Professional (Adult, Pediatric & Neonatal) (CCRN-K)',
                'Certified Clinical Research Professional (CCRP)',
                'Certified in Care Coordination and Transition Management (CCTM)',
                'Certified Dialysis Licensed Practical Worker (CD-LPN)',
                'Certified Dialysis Licensed Vocational Worker (CD-LVN)',
                'Certified Diabetes Educator (CDE)',
                'Certified Dialysis Worker (CDN)',
                'Certified Emergency Worker (CEN)',
                'Certified in Executive Nursing Practice (CENP)',
                'Certified Foot Care Worker (CFCN)',
                'Certified Flight Registered Worker (CFRN)',
                'Certified Gastroenterology Registered Worker (CGRN)',
                'Certified Heart Failure Worker (CHFN)',
                'Non-Clinical HeartFailure Worker (CHFN-K)',
                'Certified Hospice and Palliative Care Administrator (CHPCA)',
                'Certified Hospice and Palliative Licensed Worker (CHPLN)',
                'Certified Hospice and Palliative Worker (CHPN)',
                'Certified Hospice and Palliative Nursing Assistant (CHPNA)',
                'Certified Hospice and Palliative Pediatric Worker (CHPPN)',
                'Certified Health Service Administrator (CHSA)',
                'Certified in Infection Control (CIC)',
                'Occupational Health Nursing Case Management (CM)',
                'Cardiac Medicine (Adult) (CMC)',
                'Certification in Managed Care Nursing (CMCN)',
                'Certified Medical-Surgical Registered Worker (CMSRN)',
                'Certified Worker Educator (CNE)',
                'Clinical Worker Leader (CNL)',
                'Worker Manager and Leader (CNML)',
                'Certified Worker Manager and Leader (CNML)',
                'Certified Corrections Worker (CNN)',
                'Certified Nephrology Worker (CNN)',
                'Certified Nephrology Worker-Worker Practitioner (CNN-NP)',
                'Certified Corrections Worker/Manager (CNN/M)',
                'Certified Worker, Operating Room (CNOR)',
                'Certified Neuroscience Registered Worker (CNRN)',
                'Clinical Worker Specialist, Core (CNS-BC)',
                'Clinical Worker Specialist Perioperative Certification (CNS-CP)',
                'Certified Ostomy Care Worker (COCN)',
                'Certified Ostomy Care Worker-Advanced Practice (COCN-AP)',
                'Certified Occupational Health Worker (COHN)',
                'Certified Occupational Health Worker-Specialist (COHN-S)',
                'Certified Otorhinolaryngology Worker (CORLN)',
                'Certified Post Anesthesia Worker (CPAN)',
                'Certified Pediatric Emergency Worker (CPEN)',
                'Certified Pediatric Hematology Oncology Worker (CPHON)',
                'Certified Professional in Healthcare Quality (CPHQ)',
                'Certified Professional in Healthcare Risk Management (CPHRM)',
                'Certified in Perinatal Loss Care (CPLC)',
                'Certified Pediatric Worker (CPN)',
                'Certified Pediatric Worker Practitioner-Primary Care (CPNP-PC)',
                'Certified Pediatric Oncology Worker (CPON)',
                'Certified Pediatric Worker Practitioner-Acute Care (CPP-AC)',
                'Certified Plastic Surgical Worker (CPSN)',
                'Certified Radiologic Worker (CRN)',
                'Certified Registered Worker Anesthetist (CRNA)',
                'Certified Registered Worker First Assistant (CRNFA)',
                'Certified Registered Worker Infusion (CRNI)',
                'Certification for Registered Workers of Opthamology (CRNO)',
                'Certified Rehabilitation Registered Worker (CRRN)',
                'Cardiac Surgery (Adult) (CSC)',
                'Certified Transport Registered Worker (CTRN)',
                'Urologic Associate (CUA)',
                'Certified Urologic Worker Practitioner (CUNP)',
                'Certified Urologic Registered Worker (CURN)',
                'Certified Wound Care Worker (CWCN)',
                'Certified Wound Care Worker-Advanced Practice (CWCN-AP)',
                'Certified Wound Ostomy Continence Worker (CWOCN)',
                'Certified Wound Ostomy Continence Worker-Advanced Practice (CWOCN-AP)',
                'Certified Wound Ostomy Worker (CWON)',
                'Certified Wound Ostomy Worker-Advanced Practice (CWON-AP)',
                'Dermatology Certified Worker Practitioner (DCNP)',
                'Dermatology Worker Certified (DNC)',
                'Emergency Worker Practitioner (specialty certification) (ENP-BC)',
                'Family Worker Practitioner (FNP-BC)',
                'Family Worker Practitioner (FNP-C)',
                'Gerontological Clinical Worker Specialist (retired exam) (GCNS-BC)',
                'Gerontological Worker Practitioner (GNP-BC)',
                'Home Health Clinical Worker Specialist (retired exam) (HHCNS-BC)',
                'Holistic Worker, Board Certified (HN-BC)',
                'Holistic Baccalaureate Worker, Board Certified (HNB-BC)',
                'Health and Wellness Worker Coach, Board Certified (HWNC-BC)',
                'Legal Worker Consultant Certified (LNCC)',
                'Worker Coach, Board Certified (NC-BC)',
                'National Certified School Worker (NCSN)',
                'Worker Executive (NE-BC)',
                'Worker Executive, Advanced (NEA-BC)',
                'Neonatal Worker Practitioner (NNP-BC)',
                'Adult Worker Practitioner (NP-C)',
                'Oncology Certified Worker (OCN)',
                'Orthopaedic Clinical Worker Specialist - Certified (OCNS-C)',
                'Orthopaedic Worker Certified (ONC)',
                'Orthopaedic Worker Practitioner-Certified (ONP-C)',
                'Progressive Care Nursing (Adult) (PCCN)',
                'Progressive Care Knowledge Professional (Adult) (PCCN-K)',
                'Pediatric Clinical Worker Specialist (PCNS-BC)',
                'Public/Community Health Clinical Worker Specialist (retired exam) (PHCNS-BC)',
                'Pediatric Primary Care Mental Health Specialist (PHMS)',
                'Public Health Nursing, Advanced (PHNA-BC)',
                'Adult Psychiatric-Mental Health Clinical Worker Specialist (PMHCNS-BC)',
                'Child/Adolescent Psychiatric-Mental Health Clinical Worker Specialist (PMHCNS-BC)',
                'Adult Psychiatric-Mental Health Worker Practitioner (PMHNP-BC)',
                'Psychiatric-Mental Health Worker Practitioner (across the life span) (PMHNP-BC)',
                'Pediatric Primary Care Worker Practitioner (PPCNP-BC)',
                'Pediatric Advanced Life Support (PALS)',
                'Ambulatory Care Nursing (RN-BC)',
                'Cardiac-Vascular Nursing (RN-BC)',
                'Certified Vascular Worker (retired exam) (RN-BC)',
                'College Health Nursing (retired exam) (RN-BC)',
                'Community Health Nursing (retired exam) (RN-BC)',
                'Faith Community Nursing (RN-BC)',
                'General Nursing, Practice (retired exam) (RN-BC)',
                'Gerontological Nursing (RN-BC)',
                'Hemostasis Nursing (RN-BC)',
                'High-Risk Perinatal Nursing (retired exam) (RN-BC)',
                'Home Health Nursing (retired exam) (RN-BC)',
                'Informatics Nursing (RN-BC)',
                'Medical-Surgical Nursing (RN-BC)',
                'Nursing Case Management (RN-BC)',
                'Nursing Professional Development (RN-BC)',
                'Pain Management Nursing (RN-BC)',
                'Pediatric Nursing (RN-BC)',
                'Perinatal Nursing (retired exam) (RN-BC)',
                'Psychiatric-Mental Health Nursing (RN-BC)',
                'Rheumatology Nursing (RN-BC)',
                'School Nursing (retired exam) (RN-BC)',
                'Low Risk Neonatal Nursing (RNC-LRN)',
                'Maternal Newborn Nursing (RNC-MNN)',
                'Neonatal Intensive Care Nursing (RNC-NIC)',
                'Inpatient Obstetric Nursing (RNC-OB)',
                'Sexual Assault Worker Examiner - Adult/Adolescent (SANE-A)',
                'Sexual Assault Worker Examiner - Pediatric (SANE-P)',
                'Stroke Certified Registered Worker (SCRN)',
                'School Worker Practitioner (retired exam) (SNP-BC)',
                'Trauma Certified Registered Worker (TCRN)',
                'Women’s Health Care Worker Practitioner (WHNP-BC)'
            ],
            'EHRSoftwares' => [
                'Allscripts',
                'AmkaiSolutions',
                'Amrita Medical Solutions',
                'Angel Systems',
                'Askesis Development Group',
                'athenahealth',
                'Cantata Health',
                'Cerner Corporation',
                'CGI',
                'CoCentrix',
                'Credible',
                'DSS Inc.',
                'eClinicalWorks',
                'empowersystems',
                'Epic Systems',
                'Evident (CPSI)',
                'FEI Systems',
                'GE Healthcare',
                'Harris Healthcare',
                'Health Care Software (HCS)',
                'Healthland (CPSI)',
                'ICANotes',
                'Indian Health Services',
                'Infomedika',
                'InterSystems',
                'Marshfield Clinic',
                'MedConnect',
                'MedEZ',
                'MEDHOST',
                'Medicat',
                'MEDITECH',
                'Medsphere Systems Corporation',
                'Meta Healthcare IT Solutions',
                'MindLinc',
                'Morris Systems',
                'Netsmart Technologies',
                'NTT Data',
                'Optimus EMR',
                'Point Click Care',
                'Prognosis Innovation Healthcare',
                'PsyTech Solutions',
                'Qualifacts Systems',
                'Remarkable Health',
                'SigmaCare',
                'Sigmund Software',
                'Source Medical Solutions',
                'Technomad',
                'Tenzing Medical',
                'Uniform Data System for Medical Rehabilitation',
                'VeraSuite',
                'WorldVistA'
            ],
            'EHRProficiencyExp' => [
                'No experience',
                'Beginner (<1-year experience)',
                'Basic (1-2 year\'s experience)',
                'Proficient (~2-4 year\'s experience)',
                'Advanced (~5+ year\'s experience)'
            ],
            'Shift' => [
                '4-hour',
                '6-hour',
                '8-hour',
                '10-hour',
                '12-hour'
            ],
            'PreferredShift' => [
                'Day shift only',
                'Night shift only',
                'Open to day or night shift'
            ],
            'DaisyCategory' => [
                'Extraordinary Worker',
                'Team Award',
                'Worker Leader',
                'Extraordinary Nursing Student',
                'Extraordinary Nursing Faculty',
                'Lifetime Achievement Award'
            ],
            'FacilityName' => [
                'Andalusia Regional Hospital',
                'Baptist Medical Center East',
                'Central Alabama Veterans Health Care System West Campus',
                'Dale Medical Center',
                'East Alabama Medical Center',
                'Elmore Community Hospital',
                'Flowers Hospital',
                'Gadsden Regional Medical Center',
                'Hale County Hospital',
                'Jack Hughston Memorial Hospital',
                'Lake Martin Community Hospital',
                'Marshall Medical Center North',
                'Medical Center Barbour',
                'North Baldwin Infirmary',
                'Parkway Medical Center',
                'Russell Medical Center',
                'Taylor Hardin Secure Medical Facility',
                'University of South Alabama Medical Center',
                'Other'
            ]
        ];
    }
}
