<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SpecialitiesTableSeeder extends Seeder
{
    public function run()
    {
        // DB::table('specialities')->delete();
        $specialties = [
            'Acute Care',
            'Addiction Medicine',
            'Administrative',
            'Admission',
            'Adult Medicine',
            'Ambulatory Care',
            'American Sign Language Teacher',
            'Anesthesia',
            'Anesthesia Technician',
            'Apheresis',
            'Assistant Director of Nursing',
            'Assistant Manager',
            'Audiologist',
            'Behavioral Health',
            'Bereavement Specialist',
            'Biomed Technician',
            'Board Certified Behavioral Analyst (BCBA)',
            'Bone Marrow Transplant',
            'Burn ICU',
            'Cardiac Cath Lab',
            'Cardiac Progressive Care Unit',
            'Cardiac Stepdown',
            'Cardiology',
            'Cardiovascular Technologist',
            'Cardiovascular/Cardiothoracic Surgery',
            'Case Management',
            'Case Management Acute Care',
            'Case Management Home Health',
            'Case Management Insurance',
            'Cath Lab Technologist',
            'CCU - Coronary Care',
            'Centralized Cardiac Monitoring Technician',
            'Centralized Sterile Technician',
            'Certified Occupational Therapist Assistant',
            'Certified Ophthalmic Medical Technologist',
            'Certified Surgical Technologist',
            'Clerical',
            'Clinic',
            'Clinical',
            'Clinical Document Improvement Specialist',
            'Clinical Fellowship Year',
            'Clinical Lab Assistant',
            'Clinical Lab Scientist (CLS)',
            'Clinical Liaison',
            'Clinical Nurse Coordinator',
            'Clinical Nurse Specialist',
            'Clinical Support Specialist',
            'Clinical Trial',
            'Correctional',
            'Critical Care/Intensive Care',
            'CT Technologist',
            'CTICU - Cardiothoracic Intensive Care',
            'CVICU',
            'CVOR',
            'CVOR Technologist',
            'CVPICU',
            'Cytogenetics Technologist',
            'Cytotechnologist',
            'Dermatology',
            'Dialysis',
            'Dialysis Technician',
            'Dietary Aide',
            'Director of Nursing',
            'Dosimetrist',
            'DOU - Direct Observation Unit',
            'Echo Technician',
            'Echo Technologist',
            'Echo-Vascular Technician',
            'ECMO',
            'ED - Emergency Department',
            'Educator',
            'EEG Technician',
            'EEG Technologist',
            'EKG Technician',
            'Electrophysiology Lab',
            'Electrophysiology Technician',
            'Emergency Medicine',
            'EMT / ER Technician',
            'Endocrinology',
            'Endoscopy',
            'Endoscopy Technician',
            'Faculty',
            'Family Practice',
            'Field Supervisor',
            'First Assist',
            'First Assist Technician',
            'Flight Nurse or Critical Care Flight Nurse',
            'Float',
            'Gastroenterology',
            'General Surgery',
            'Geriatrics',
            'Gerontology',
            'GI Lab',
            'Health Services Administrator',
            'Hematology & Oncology',
            'Histology Technician',
            'Home Health',
            'Hospice',
            'Hospitalist',
            'House Supervisor',
            'ICU - Intensive Care Unit',
            'Infection Control',
            'Infusion',
            'Integrative Health',
            'Intermediate Care',
            'Internal Medicine',
            'Interventional Radiology',
            'Interventional Radiology Technologist',
            'Labor and Delivery',
            'Lactation RN',
            'Licensed Clinical Social Worker',
            'Licensed Independent Clinical Social Worker',
            'Licensed Marriage and Family Therapist',
            'Licensed Professional Clinical Counselor',
            'Long Term Acute Care',
            'Long Term Care',
            'Mammography Technician',
            'Manager',
            'Master of Social Work',
            'Maternal - Newborn',
            'Med Surg',
            'Med Surg / Telemetry',
            'Medical Lab Scientist',
            'Medical Lab Technician',
            'Medical Technologist',
            'Medical Unit',
            'Mental Health',
            'MICU - Medical Intensive Care Unit',
            'Midwife',
            'Mobile Testing',
            'Monitor Technician',
            'MRI Technologist',
            'Multi-modality Technologist',
            'Neonatology',
            'Nephrology',
            'Neuro ICU',
            'Neuro PCU',
            'Neurology',
            'Neurosurgery',
            'New Graduate',
            'NICU - Neonatal Intensive Care',
            'Nuclear Medicine Technologist',
            'Nurse Extern',
            'Nurse Navigator',
            'Nurse Resident',
            'Nursing Home',
            'OB Technician',
            'Obstetrics / Gynecology',
            'Occupational Health',
            'Occupational Medicine',
            'Occupational Therapist',
            'Occupational Therapist Assistant',
            'Ophthalmic Assistant',
            'Ophthalmic Technician',
            'Ophthalmology',
            'OR - Operating Room',
            'OR Circulate',
            'OR Scrub RN',
            'Ortho Trauma',
            'Orthopedic Neurology',
            'Orthopedic Surgery',
            'Orthopedics',
            'Otolaryngology',
            'PACU - Post Anesthetic Care',
            'Pain Management',
            'Palliative',
            'Palliative Care',
            'Paramedic',
            'Pathologists Assistant',
            'Pathology Assistant',
            'Patient Care Tech',
            'PCU - Progressive Care Unit',
            'Pediatric Cardiac Cath Lab',
            'Pediatric CVOR',
            'Pediatric Hematology / Oncology',
            'Pediatric Hospitalist',
            'Pediatric MRI Technologist',
            'Pediatric PCU - Progressive Care Unit',
            'Pediatric Radiology Technologist',
            'Pediatrics',
            'Pediatrics CVICU',
            'Pediatrics ER - Emergency Room',
            'Pediatrics OR - Operating Room',
            'Pediatrics PACU - Post Anesthetic Care',
            'Perfusionist',
            'Perioperative',
            'Pharmacist',
            'Pharmacy Technician',
            'Phlebotomist',
            'Physical Therapist',
            'Physical Therapy Assistant',
            'Physicist',
            'PICU - Pediatric Intensive Care',
            'PMR Physical Medicine & Rehab',
            'Polysomnographer',
            'Post Partum',
            'Preoperative',
            'Private Duty',
            'Psychiatric',
            'Psychiatry',
            'Psychologist',
            'Public Health',
            'Pulmonology',
            'Radiation Therapist',
            'Radiology',
            'Radiology Technician',
            'Radiology Technologist',
            'RDCD Dietician',
            'Recreation/Recreational Therapist',
            'Recruiter',
            'Registered Respiratory Therapist',
            'Rehab Technician',
            'Rehabilitation',
            'Rehabilitation Therapist',
            'Research / Clinical Research',
            'Respiratory Care Practitioner',
            'Respiratory Technician',
            'Respiratory Therapist',
            'Risk Manager',
            'School Nurse',
            'School Psychologist (Certified)',
            'SICU - Surgical Intensive Care',
            'Skilled Nursing Facility',
            'Social Worker',
            'Sonography Technician',
            'Special Education Teacher',
            'Special Procedure Technician',
            'Special Procedures',
            'Special Procedures Technologist',
            'Speech Language Pathologist',
            'Speech Language Pathologist Assistant (SLPA)',
            'Stepdown',
            'Sterile Processing Technician',
            'Stroke',
            'Surgical First Assistant',
            'Surgical ICU Stepdown',
            'Surgical Oncology',
            'Surgical Technician',
            'Surgical Technologist',
            'System Float',
            'Teacher of the Deaf and Hard of Hearing',
            'Telehealth',
            'Telemetry',
            'Telemetry PCU',
            'Telemetry Technician',
            'Transplant',
            'Transport',
            'Transporter Multimodality Technician',
            'Trauma ICU',
            'Trauma Program Manager',
            'Ultrasound Technologist',
            'Urgent Care',
            'Urology',
            'Utilization Review',
            'Vaccination',
            'Vascular Access',
            'Vascular Interventional Technician',
            'Vascular Technologist',
            'Vision Assistant',
            'Visual Impairments Teacher',
            'Women\'s Services',
            'Wound Care',
            'X-Ray Technician',
            'In-Patient',
            'Outpatient Surgery',
            'Crisis Stabilization Unit',
        ];

        foreach ($specialties as $specialty) {
            //$professionId = DB::table('professions')->inRandomOrder()->value('id');
            if (DB::table('specialities')->where('full_name', $specialty)->exists()) {
                continue;
            }
            DB::table('specialities')->insert([
                //'id' => Str::uuid(),
                //'Profession_id' => $professionId,
                'full_name' => $specialty,
                'short_name' => strtolower(str_replace(' ', '_', $specialty)),
            ]);
        }
    }
}
