<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            [
                'id' => '1',
                'name' => 'Alabama',
                'country_id' => 1,
                'fips_code' => 'US01',
                'iso2' => 'AL',
                'type' => 'State',
                'latitude' => 32.806671,
                'longitude' => -86.79113,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q173',
                'deleted_at' => null,
            ],
            [
                'id'=> '2',
                'name' => 'Alaska',
                'country_id' => 1,
                'fips_code' => 'US02',
                'iso2' => 'AK',
                'type' => 'State',
                'latitude' => 61.370716,
                'longitude' => -152.404419,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q797',
                'deleted_at' => null,
            ],
            [
                'id'=> '3',
                'name' => 'Arizona',
                'country_id' => 1,
                'fips_code' => 'US04',
                'iso2' => 'AZ',
                'type' => 'State',
                'latitude' => 33.729759,
                'longitude' => -111.431221,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q816',
                'deleted_at' => null,
            ],
            [
                'id'=> '4',
                'name' => 'Arkansas',
                'country_id' => 1,
                'fips_code' => 'US05',
                'iso2' => 'AR',
                'type' => 'State',
                'latitude' => 34.969704,
                'longitude' => -92.373123,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q1612',
                'deleted_at' => null,
            ],
            [
                'id'=> '5',
                'name' => 'California',
                'country_id' => 1,
                'fips_code' => 'US06',
                'iso2' => 'CA',
                'type' => 'State',
                'latitude' => 36.116203,
                'longitude' => -119.681564,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q99',
                'deleted_at' => null,
            ],
            [
                'id'=> '6',
                'name' => 'Colorado',
                'country_id' => 1,
                'fips_code' => 'US08',
                'iso2' => 'CO',
                'type' => 'State',
                'latitude' => 39.059811,
                'longitude' => -105.311104,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q1261',
                'deleted_at' => null,
            ],
            [
                'id'=> '7',
                'name' => 'Connecticut',
                'country_id' => 1,
                'fips_code' => 'US09',
                'iso2' => 'CT',
                'type' => 'State',
                'latitude' => 41.597782,
                'longitude' => -72.755371,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q779',
                'deleted_at' => null,
            ],
            [
                'id'=> '8',
                'name' => 'Delaware',
                'country_id' => 1,
                'fips_code' => 'US10',
                'iso2' => 'DE',
                'type' => 'State',
                'latitude' => 39.318523,
                'longitude' => -75.507141,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q1396',
                'deleted_at' => null,
            ],
            [   'id'=> '9',
                'name' => 'Florida',
                'country_id' => 1,
                'fips_code' => 'US12',
                'iso2' => 'FL',
                'type' => 'State',
                'latitude' => 27.766279,
                'longitude' => -81.686783,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q812',
                'deleted_at' => null,
            ],
            [
                'id'=> '10',
                'name' => 'Georgia',
                'country_id' => 1,
                'fips_code' => 'US13',
                'iso2' => 'GA',
                'type' => 'State',
                'latitude' => 33.040619,
                'longitude' => -83.643074,
                'created_at' => now(),
                'updated_at' => now(),
                'wikiDataId' => 'Q1428',
                'deleted_at' => null,
            ],



                [
                    'id'=> '11',
                    'name' => 'Hawaii',
                    'country_id' => 1,
                    'fips_code' => 'US15',
                    'iso2' => 'HI',
                    'type' => 'State',
                    'latitude' => 21.094318,
                    'longitude' => -157.498337,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q782',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '12',
                    'name' => 'Idaho',
                    'country_id' => 1,
                    'fips_code' => 'US16',
                    'iso2' => 'ID',
                    'type' => 'State',
                    'latitude' => 44.240459,
                    'longitude' => -114.478828,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1213',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '13',
                    'name' => 'Illinois',
                    'country_id' => 1,
                    'fips_code' => 'US17',
                    'iso2' => 'IL',
                    'type' => 'State',
                    'latitude' => 40.349457,
                    'longitude' => -88.986137,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1204',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '14',
                    'name' => 'Indiana',
                    'country_id' => 1,
                    'fips_code' => 'US18',
                    'iso2' => 'IN',
                    'type' => 'State',
                    'latitude' => 39.849426,
                    'longitude' => -86.258278,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1486',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '15',
                    'name' => 'Iowa',
                    'country_id' => 1,
                    'fips_code' => 'US19',
                    'iso2' => 'IA',
                    'type' => 'State',
                    'latitude' => 42.011539,
                    'longitude' => -93.210526,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1549',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '16',
                    'name' => 'Kansas',
                    'country_id' => 1,
                    'fips_code' => 'US20',
                    'iso2' => 'KS',
                    'type' => 'State',
                    'latitude' => 38.5266,
                    'longitude' => -96.726486,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1553',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '17',
                    'name' => 'Kentucky',
                    'country_id' => 1,
                    'fips_code' => 'US21',
                    'iso2' => 'KY',
                    'type' => 'State',
                    'latitude' => 37.66814,
                    'longitude' => -84.670067,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1603',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '18',
                    'name' => 'Louisiana',
                    'country_id' => 1,
                    'fips_code' => 'US22',
                    'iso2' => 'LA',
                    'type' => 'State',
                    'latitude' => 31.169546,
                    'longitude' => -91.867805,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1659',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '19',
                    'name' => 'Maine',
                    'country_id' => 1,
                    'fips_code' => 'US23',
                    'iso2' => 'ME',
                    'type' => 'State',
                    'latitude' => 44.693947,
                    'longitude' => -69.381927,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q759',
                    'deleted_at' => null,
                ],
                [
                    'id'=> '20',
                    'name' => 'Maryland',
                    'country_id' => 1,
                    'fips_code' => 'US24',
                    'iso2' => 'MD',
                    'type' => 'State',
                    'latitude' => 39.063946,
                    'longitude' => -76.802101,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'wikiDataId' => 'Q1390',
                    'deleted_at' => null,
                ],

                    [
                        'id'=> '21',
                        'name' => 'Massachusetts',
                        'country_id' => 1,
                        'fips_code' => 'US25',
                        'iso2' => 'MA',
                        'type' => 'State',
                        'latitude' => 42.230171,
                        'longitude' => -71.530106,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q771',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '22',
                        'name' => 'Michigan',
                        'country_id' => 1,
                        'fips_code' => 'US26',
                        'iso2' => 'MI',
                        'type' => 'State',
                        'latitude' => 43.326618,
                        'longitude' => -84.536095,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1166',
                        'deleted_at' => null,
                    ],
                    [
                            'id'=> '23',
                        'name' => 'Minnesota',
                        'country_id' => 1,
                        'fips_code' => 'US27',
                        'iso2' => 'MN',
                        'type' => 'State',
                        'latitude' => 45.694454,
                        'longitude' => -93.900192,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1527',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '24',
                        'name' => 'Mississippi',
                        'country_id' => 1,
                        'fips_code' => 'US28',
                        'iso2' => 'MS',
                        'type' => 'State',
                        'latitude' => 32.741646,
                        'longitude' => -89.678696,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1491',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '25',
                        'name' => 'Missouri',
                        'country_id' => 1,
                        'fips_code' => 'US29',
                        'iso2' => 'MO',
                        'type' => 'State',
                        'latitude' => 38.456085,
                        'longitude' => -92.288368,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1589',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '26',
                        'name' => 'Montana',
                        'country_id' => 1,
                        'fips_code' => 'US30',
                        'iso2' => 'MT',
                        'type' => 'State',
                        'latitude' => 46.921925,
                        'longitude' => -110.454353,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q798',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '27',
                        'name' => 'Nebraska',
                        'country_id' => 1,
                        'fips_code' => 'US31',
                        'iso2' => 'NE',
                        'type' => 'State',
                        'latitude' => 41.12537,
                        'longitude' => -98.268082,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1554',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '28',
                        'name' => 'Nevada',
                        'country_id' => 1,
                        'fips_code' => 'US32',
                        'iso2' => 'NV',
                        'type' => 'State',
                        'latitude' => 38.313515,
                        'longitude' => -117.055374,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1227',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '29',
                        'name' => 'New Hampshire',
                        'country_id' => 1,
                        'fips_code' => 'US33',
                        'iso2' => 'NH',
                        'type' => 'State',
                        'latitude' => 43.452492,
                        'longitude' => -71.563896,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1408',
                        'deleted_at' => null,
                    ],
                    [
                        'id'=> '30',
                        'name' => 'New Jersey',
                        'country_id' => 1,
                        'fips_code' => 'US34',
                        'iso2' => 'NJ',
                        'type' => 'State',
                        'latitude' => 40.298904,
                        'longitude' => -74.521011,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'wikiDataId' => 'Q1408',
                        'deleted_at' => null,
                    ],

                        [
                            'id'=> '31',
                            'name' => 'New Mexico',
                            'country_id' => 1,
                            'fips_code' => 'US35',
                            'iso2' => 'NM',
                            'type' => 'State',
                            'latitude' => 34.840515,
                            'longitude' => -106.248482,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1566',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '32',
                            'name' => 'New York',
                            'country_id' => 1,
                            'fips_code' => 'US36',
                            'iso2' => 'NY',
                            'type' => 'State',
                            'latitude' => 42.165726,
                            'longitude' => -74.948051,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1384',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '33',
                            'name' => 'North Carolina',
                            'country_id' => 1,
                            'fips_code' => 'US37',
                            'iso2' => 'NC',
                            'type' => 'State',
                            'latitude' => 35.630066,
                            'longitude' => -79.806419,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1453',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '34',
                            'name' => 'North Dakota',
                            'country_id' => 1,
                            'fips_code' => 'US38',
                            'iso2' => 'ND',
                            'type' => 'State',
                            'latitude' => 47.528912,
                            'longitude' => -99.784012,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1201',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '35',
                            'name' => 'Ohio',
                            'country_id' => 1,
                            'fips_code' => 'US39',
                            'iso2' => 'OH',
                            'type' => 'State',
                            'latitude' => 40.388783,
                            'longitude' => -82.764915,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1397',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '36',
                            'name' => 'Oklahoma',
                            'country_id' => 1,
                            'fips_code' => 'US40',
                            'iso2' => 'OK',
                            'type' => 'State',
                            'latitude' => 35.565342,
                            'longitude' => -96.928917,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1649',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '37',
                            'name' => 'Oregon',
                            'country_id' => 1,
                            'fips_code' => 'US41',
                            'iso2' => 'OR',
                            'type' => 'State',
                            'latitude' => 44.572021,
                            'longitude' => -122.070938,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q824',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '38',
                            'name' => 'Pennsylvania',
                            'country_id' => 1,
                            'fips_code' => 'US42',
                            'iso2' => 'PA',
                            'type' => 'State',
                            'latitude' => 40.590752,
                            'longitude' => -77.209755,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1376',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '39',
                            'name' => 'Rhode Island',
                            'country_id' => 1,
                            'fips_code' => 'US44',
                            'iso2' => 'RI',
                            'type' => 'State',
                            'latitude' => 41.680893,
                            'longitude' => -71.51178,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1386',
                            'deleted_at' => null,
                        ],
                        [
                            'id'=> '40',
                            'name' => 'South Carolina',
                            'country_id' => 1,
                            'fips_code' => 'US45',
                            'iso2' => 'SC',
                            'type' => 'State',
                            'latitude' => 33.856892,
                            'longitude' => -80.945007,
                            'created_at' => now(),
                            'updated_at' => now(),
                            'wikiDataId' => 'Q1454',
                            'deleted_at' => null,
                        ],
                            [
                                'id'=> '41',
                                'name' => 'South Dakota',
                                'country_id' => 1,
                                'fips_code' => 'US46',
                                'iso2' => 'SD',
                                'type' => 'State',
                                'latitude' => 44.299782,
                                'longitude' => -99.438828,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1211',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '42',
                                'name' => 'Tennessee',
                                'country_id' => 1,
                                'fips_code' => 'US47',
                                'iso2' => 'TN',
                                'type' => 'State',
                                'latitude' => 35.747845,
                                'longitude' => -86.692345,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1501',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '43',
                                'name' => 'Texas',
                                'country_id' => 1,
                                'fips_code' => 'US48',
                                'iso2' => 'TX',
                                'type' => 'State',
                                'latitude' => 31.054487,
                                'longitude' => -97.563461,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1439',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '44',
                                'name' => 'Utah',
                                'country_id' => 1,
                                'fips_code' => 'US49',
                                'iso2' => 'UT',
                                'type' => 'State',
                                'latitude' => 40.150032,
                                'longitude' => -111.862434,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q829',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '45',
                                'name' => 'Vermont',
                                'country_id' => 1,
                                'fips_code' => 'US50',
                                'iso2' => 'VT',
                                'type' => 'State',
                                'latitude' => 44.045876,
                                'longitude' => -72.710686,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1696',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '46',
                                'name' => 'Virginia',
                                'country_id' => 1,
                                'fips_code' => 'US51',
                                'iso2' => 'VA',
                                'type' => 'State',
                                'latitude' => 37.769337,
                                'longitude' => -78.169968,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1370',
                                'deleted_at' => null,
                            ],
                            [
                                    'id'=> '47',
                                'name' => 'Washington',
                                'country_id' => 1,
                                'fips_code' => 'US53',
                                'iso2' => 'WA',
                                'type' => 'State',
                                'latitude' => 47.400902,
                                'longitude' => -121.490494,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1223',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '48',
                                'name' => 'West Virginia',
                                'country_id' => 1,
                                'fips_code' => 'US54',
                                'iso2' => 'WV',
                                'type' => 'State',
                                'latitude' => 38.491226,
                                'longitude' => -80.954158,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q802',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '49',
                                'name' => 'Wisconsin',
                                'country_id' => 1,
                                'fips_code' => 'US55',
                                'iso2' => 'WI',
                                'type' => 'State',
                                'latitude' => 44.268543,
                                'longitude' => -89.616508,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1490',
                                'deleted_at' => null,
                            ],
                            [
                                'id'=> '50',
                                'name' => 'Wyoming',
                                'country_id' => 1,
                                'fips_code' => 'US56',
                                'iso2' => 'WY',
                                'type' => 'State',
                                'latitude' => 42.755966,
                                'longitude' => -107.30249,
                                'created_at' => now(),
                                'updated_at' => now(),
                                'wikiDataId' => 'Q1212',
                                'deleted_at' => null,
                            ],
        ];


        // Inserting states into the database
        DB::table('states')->insert($states);
    }
}
