<?php

namespace App\Providers;

use Faker\Generator;
use Faker\Provider\Base;

class FantasyNameProvider extends Base
{
    protected static $fantasyNames = [
        'fantasyNames' => [
            'Tom Hanks',
            'Meryl Streep',
            'Leonardo DiCaprio',
            'Scarlett Johansson',
            'Brad Pitt',
            'Angelina Jolie',
            'Denzel Washington',
            'Emma Stone',
            'Morgan Freeman',
            'Julia Roberts',
            'Robert De Niro',
            'Charlize Theron',
            'Will Smith',
            'Jennifer Lawrence',
            'Johnny Depp',
            'Nicole Kidman',
            'Matt Damon',
            'Cate Blanchett',
            'Samuel L. Jackson',
            'Natalie Portman',
            'George Clooney',
            'Sandra Bullock',
            'Christian Bale',
            'Anne Hathaway',
            'Jake Gyllenhaal',
            'Kate Winslet',
            'Daniel Day-Lewis',
            'Amy Adams',
            'Ryan Gosling',
            'Helen Mirren',
            'Hugh Jackman',
            'Reese Witherspoon',
            'Mark Wahlberg',
            'Judi Dench',
            'Tom Cruise',
            'Viola Davis',
            'Chris Hemsworth',
            'Emily Blunt',
            'Bradley Cooper',
            'Emma Watson',
            'Michael Fassbender',
            'Gwyneth Paltrow',
            'Colin Farrell',
            'Rachel McAdams',
            'John Travolta',
            'Cameron Diaz',
            'Liam Neeson',
            'Kirsten Dunst',
            'Keanu Reeves',
            'Diane Keaton',
            'Chris Evans',
            'Angelica Huston',
            'Jason Statham',
            'Uma Thurman',
            'Anthony Hopkins',
            'Meg Ryan',
            'Kevin Hart',
            'Michelle Pfeiffer',
            'Seth Rogen',
            'Jennifer Aniston',
            'Ewan McGregor',
            'Charlton Heston',
            'Diane Kruger',
            'Chris Pratt',
            'Helen Hunt',
            'Gerard Butler',
            'Jane Fonda',
            'Orlando Bloom',
            'Anne Bancroft',
            'Seth MacFarlane',
            'Diane Lane',
            'Daniel Craig',
            'Jessica Chastain',
            'Owen Wilson',
            'Glenn Close',
            'Shia LaBeouf',
            'Isla Fisher',
            'Jamie Foxx',
            'Sienna Miller',
            'Eddie Redmayne',
            'Winona Ryder',
            'Patrick Stewart',
            'Zooey Deschanel',
            'Ben Affleck',
            'Jodie Foster',
            'Tom Hardy',
            'Catherine Zeta-Jones',
            'James Franco',
            'Sarah Jessica Parker',
            'Hugh Grant',
            'Claire Danes',
            'Aaron Paul',
            'Naomi Watts',
            'Joseph Gordon-Levitt',
            'Salma Hayek',
            'Paul Rudd',
            'Laura Linney',
            'Chris Pine',
            'Jessica Lange',
            'Jake Johnson',
            'Taylor Swift',
            'Zayn Malik',
            'Elton John',
            'Pink',
            'David Bowie',
            'Lana Del Rey',
            'The Beatles',
            'Jason Derulo',
            'Bon Jovi',
            'Michael Jackson',
            'Sam Hunt',
            'Enrique Iglesias',
            'Metallica',
            'Christina Aguilera',
            'Fleetwood Mac',
            'Jennifer Lopez',
            'John Mayer',
            'Keith Urban',
            'Luke Bryan',
            'One Direction',
            'Pitbull',
            'Gwen Stefani',
            'Ozzy Osbourne',
            'The Rolling Stones',
            'Usher',
            'Shakira',
            'Ariana Grande',
            'Miley Cyrus',
            'Florence + The Machine',
            'Mariah Carey',
            'Shania Twain',
            'Katy Perry',
            'Stevie Wonder',
            'Blake Shelton',
            'Carrie Underwood',
            'The Chainsmokers',
            'Niall Horan',
            'Iggy Azalea',
            'Ariana Grande',
            'Taylor Swift',
            'Post Malone',
            'Ed Sheeran',
            'Bruno Mars',
            'Zara Larsson',
            'Calvin Harris',
            'Hozier',
            'Imagine Dragons',
            'The Weeknd',
            'Nicki Minaj',
            'James Bay',
            'Shawn Mendes',
            'Demi Lovato',
            'Justin Bieber',
            'OneRepublic',
            'Khalid',
            'Sam Smith',
            'Drake',
            'Pink',
            'Lady Gaga',
            'Selena Gomez',
            'Coldplay',
            'Adele',
            'Beyoncé Knowles',
            'AATROX',
            'AHRI',
            'AKALI',
            'AKSHAN',
            'ALISTAR',
            'AMUMU',
            'ANIVIA',
            'ANNIE',
            'APHELIOS',
            'ASHE',
            'AURELION SOL',
            'AZIR',
            'BARD',
            'BEL\'VETH',
            'BLITZCRANK',
            'BRAND',
            'BRAUM',
            'BRIAR',
            'CAITLYN',
            'CAMILLE',
            'CASSIOPEIA',
            'CHO\'GATH',
            'CORKI',
            'DARIUS',
            'DIANA',
            'DR. MUNDO',
            'DRAVEN',
            'EKKO',
            'ELISE',
            'EVELYNN',
            'EZREAL',
            'FIDDLESTICKS',
            'FIORA',
            'FIZZ',
            'GALIO',
            'GANGPLANK',
            'GAREN',
            'GNAR',
            'GRAGAS',
            'GRAVES',
            'GWEN',
            'HECARIM',
            'HEIMERDINGER',
            'HWEI',
            'ILLAOI',
            'IRELIA',
            'IVERN',
            'JANNA',
            'JARVAN IV',
            'JAX',
            'JAYCE',
            'JHIN',
            'JINX',
            'K\'SANTE',
            'KAI\'SA',
            'KALISTA',
            'KARMA',
            'KARTHUS',
            'KASSADIN',
            'KATARINA',
            'KAYLE',
            'KAYN',
            'KENNEN',
            'KHA\'ZIX',
            'KINDRED',
            'KLED',
            'KOG\'MAW',
            'LEBLANC',
            'LEE SIN',
            'LEONA',
            'LILLIA',
            'LISSANDRA',
            'LUCIAN',
            'LULU',
            'LUX',
            'MALPHITE',
            'MALZAHAR',
            'MAOKAI',
            'MASTER YI',
            'MILIO',
            'MISS FORTUNE',
            'MORDEKAISER',
            'MORGANA',
            'NAAFIRI',
            'NAMI',
            'NASUS',
            'NAUTILUS',
            'NEEKO',
            'NIDALEE',
            'NILAH',
            'NOCTURNE',
            'NUNU & WILLUMP',
            'OLAF',
            'ORIANNA',
            'ORNN',
            'PANTHEON',
            'POPPY',
            'PYKE',
            'QIYANA',
            'QUINN',
            'RAKAN',
            'RAMMUS',
            'REK\'SAI',
            'RELL',
            'RENATA GLASC',
            'RENEKTON',
            'RENGAR',
            'RIVEN',
            'RUMBLE',
            'RYZE',
            'SAMIRA',
            'SEJUANI',
            'SENNA',
            'SERAPHINE',
            'SETT',
            'SHACO',
            'SHEN',
            'SHYVANA',
            'SINGED',
            'SION',
            'SIVIR',
            'SKARNER',
            'SONA',
            'SORAKA',
            'SWAIN',
            'SYLAS',
            'SYNDRA',
            'TAHM KENCH',
            'TALIYAH',
            'TALON',
            'TARIC',
            'TEEMO',
            'THRESH',
            'TRISTANA',
            'TRUNDLE',
            'TRYNDAMERE',
            'TWISTED FATE',
            'TWITCH',
            'UDYR',
            'URGOT',
            'VARUS',
            'VAYNE',
            'VEIGAR',
            'VEL\'KOZ',
            'VEX',
            'VI',
            'VIEGO',
            'VIKTOR',
            'VLADIMIR',
            'VOLIBEAR',
            'WARWICK',
            'WUKONG',
            'XAYAH',
            'XERATH',
            'XIN ZHAO',
            'YASUO',
            'YONE',
            'YORICK',
            'YUUMI',
            'ZAC',
            'ZED',
            'ZERI',
            'ZIGGS',
            'ZILEAN',
            'ZOE',
            'ABADDON',
            'ALCHEMIST',
            'ANCIENT APPARITION',
            'ANTI-MAGE',
            'ARC WARDEN',
            'AXE',
            'BANE',
            'BATRIDER',
            'BEASTMASTER',
            'BLOODSEEKER',
            'BOUNTY HUNTER',
            'BREWMASTER',
            'BRISTLEBACK',
            'BROODMOTHER',
            'CENTAUR WARRUNNER',
            'CHAOS KNIGHT',
            'CHEN',
            'CLINKZ',
            'CLOCKWERK',
            'CRYSTAL MAIDEN',
            'DARK SEER',
            'DARK WILLOW',
            'DAWNBREAKER',
            'DAZZLE',
            'DEATH PROPHET',
            'DISRUPTOR',
            'DOOM',
            'DRAGON KNIGHT',
            'DROW RANGER',
            'EARTH SPIRIT',
            'EARTHSHAKER',
            'ELDER TITAN',
            'EMBER SPIRIT',
            'ENCHANTRESS',
            'ENIGMA',
            'FACELESS VOID',
            'GRIMSTROKE',
            'GYROCOPTER',
            'HOODWINK',
            'HUSKAR',
            'INVOKER',
            'IO',
            'JAKIRO',
            'JUGGERNAUT',
            'KEEPER OF THE LIGHT',
            'KELLY',
            'KUNKKA',
            'LEGION COMMANDER',
            'LESHRAC',
            'LICH',
            'LIFESTEALER',
            'LINA',
            'LION',
            'LONE DRUID',
            'LUNA',
            'LYCAN',
            'MAGNUS',
            'MARS',
            'MEDUSA',
            'MEEP',
            'MIRANA',
            'MONKEY KING',
            'MORPHLING',
            'NAGA SIREN',
            'NATURE\'S PROPHET',
            'NECROPHOS',
            'NIGHT STALKER',
            'NYX ASSASSIN',
            'OGRE MAGI',
            'OMNIKNIGHT',
            'ORACLE',
            'OUTWORLD DESTROYER',
            'PA',
            'PANGOLIER',
            'PHANTOM ASSASSIN',
            'PHANTOM LANCER',
            'PHOENIX',
            'PUDGE',
            'PUGNA',
            'QUEEN OF PAIN',
            'RAZOR',
            'RIKI',
            'RUBICK',
            'SAND KING',
            'SHADOW DEMON',
            'SHADOW FIEND',
            'SHADOW SHAMAN',
            'SILENCER',
            'SKYWRATH MAGE',
            'SLARDAR',
            'SLARK',
            'SNAPFIRE',
            'SNIPER',
            'SPECTRE',
            'SPIRIT BREAKER',
            'STORM SPIRIT',
            'SVEN',
            'TECHIES',
            'TEMPLAR ASSASSIN',
            'TERRORBLADE',
            'TIDEHUNTER',
            'TIMBERSAW',
            'TINKER',
            'TINY',
            'TREANT PROTECTOR',
            'TROLL WARLORD',
            'TUSK',
            'UNDERLORD',
            'UNDYING',
            'URSA',
            'VENGEFUL SPIRIT',
            'VENOMANCER',
            'VIOLET',
            'VIPER',
            'VISAGE',
            'VOID SPIRIT',
            'WARLOCK',
            'WEAVER',
            'WINDRANGER',
            'WINTER WYVERN',
            'WITCH DOCTOR',
            'WRAITH KING',
            'ZEUS',
            'ABUMOJANDIS',
            'BANNERJEE',
            'BIJAZ',
            'BIKOUROS',
            'BRONSO OF IX',
            'CAHUEIT',
            'DALAMAK',
            'DHURI',
            'DJEDIDA',
            'EDRIC',
            'GHANIMA ATREIDES',
            'HAYT',
            'HOBAR',
            'LEGG',
            'LETO ATREIDES II',
            'LICHNA',
            'RAJIFIRI',
            'RASIR',
            'SAAJID',
            'SCYTALE',
            'SHISHAKLI',
            'SON OF FAROK',
            'TANDIS',
            'TASMIN',
            'TECRUBE',
            'TIBANA',
            'UMBUL',
            'UNNAMED QIZARA',
            'UNNAMED GUIDE',
            'ZAAL ABEDI JALAL',
            'ASSAN TARIQ',
            'BEHALETH',
            'BUER AGARVES',
            'CHODA',
            'DALAK',
            'FARAD\'N CORRINO',
            'GEORAD',
            'GHADHEAN AL-FALI',
            'HARUM',
            'JAVID',
            'KAUSAR',
            'LU TUNG PIN',
            'MANRI',
            'MELIDES',
            'NAMRI',
            'MUJAHID JAFQAT',
            'MURIZ',
            'PALIMBASHA',
            'ESSAS PAYMON',
            'RAJIA',
            'SABIHA',
            'SABIT REKUSH',
            'SENNACHERIB',
            'SHAKIR ALI',
            'SHAKKAD THE WISE',
            'SHEBA',
            'STILGAR',
            'TAGIR MOHANDIS',
            'THATTA',
            'TYEKANIK',
            'YAKUP ABAD',
            'ZEBATALEPH',
            'ZIA',
            'ZIAMAD',
            'ZIARENKA',
            'VALEFOR AKELI',
            'ALINE',
            'AMPRE',
            'ANOUK',
            'AURELIUS VENPORT',
            'DURO NUNEPI',
            'EKNEKOSK',
            'FAROULA',
            'GARUN OF TUONO',
            'HADI BENOTTO',
            'HUTYE',
            'HWI NOREE',
            'IKONICRE',
            'ININEG',
            'INMEIR',
            'IRTI',
            'IYO KOBAT',
            'KIEUEMO',
            'KWUTEG',
            'LULI',
            'MALKY',
            'MAMULUT',
            'MARCUS CLAIRE LUYSEYAL',
            'MEMAR',
            'MONEO ATREIDES',
            'NAYLA',
            'NOAH ARKWRIGHT',
            'NORMA CENVA',
            'LYLYO NYSHAE',
            'OALA',
            'ONEMAO',
            'OTHWI YAKE',
            'QUINTINIUS VIOLET CHENOEH',
            'RADI',
            'REBETH VREEB',
            'SETUSE',
            'SIONA ATREIDES',
            'SIRAFA',
            'SYAKSA',
            'TAW',
            'TAWSUOKO',
            'TEISHAR',
            'TERTIUS EILEEN ANTEAC',
            'TOPRI',
            'ULOT',
            'ZAALENKA'],
             "first_name" => [
                "Balgruuf",
                "Ralof",
                "Hadvar",
                "Irileth",
                "Gormlaith",
                "Farengar",
                "Felldir",
                "Hakon",
                "Iddra",
                "Malborn",
                "Tsun",
                "Ysgramor",
                "Tsun",
                "Gerdur",
                "Dirge",
                "Orgnar",
                "Septimus",
                "Urag",
                "Brynjolf",
                "Faralda",
                "Vignar",
                "Elenwen",
                "Rulindil",
                "Gissur",
                "Drahff",
                "Hewnon",
                "Gian",
                "Sulla",
                "Umana",
                "J'darr",
                "Astrid",
                "Nazir",
                "Maliq",
                "Babette",
                "Gabriella",
                "Festus",
                "Arnbjorn",
                "Veezara",
                "Kodlak",
                "Aela",
                "Farkas",
                "Vilkas",
                "Skjor",
                "Athis",
                "Njada",
                "Ria",
                "Torvar",
                "Brill",
                "Eorlund",
                "Tilma",
                "Hestla",
                "Askar",
                "Mercer",
                "Delvin",
                "Vex",
                "Tonilia",
                "Sapphire",
                "Cynric",
                "Niruin",
                "Rune",
                "Thrynn",
                "Vipir",
                "Garthar",
                "Ravyn",
                "Etienne",
                "Molgrom",
                "Karliah",
                "Syndus",
                "Vanryth",
                "Gulum-Ei",
                "Enthir",
                "Niranye",
                "Endon",
                "Mallus",
                "Athel",
                "Glover",
                "Erikur",
                "Ri'saad",
                "Atahbah",
                "Ma'randru-jo",
                "Khayla",
                "Ahkari",
                "Zaynabi",
                "Dro'marash",
                "Kharjo",
                "Ma'dran",
                "Ma'jhad",
                "Ra'zhinda",
                "Mjoll",
                "Brand-shei",
                "Inigo"
            ],
        "last_name" => [
            "The Old",
            "The Greater",
            "The Lesser",
            "One-Eye",
            "Golden-Hilt",
            "Secret-Fire",
            "Septim",
            "Signus",
            "gro-Shub",
            "Gray-Mane",
            "Black-Skeever",
            "The Fist",
            "Krex",
            "Whitemane",
            "Hunter",
            "Stonearm",
            "The Haggard",
            "The Unbroken",
            "The Man",
            "Ember-Master",
            "Battle-Born",
            "Black-Briar",
            "Lothaire",
            "Frey",
            "Mallory",
            "Endell",
            "The Fleet",
            "Imyan",
            "Rarnis",
            "Twice-Killed",
            "Gatharian",
            "Maccius",
            "Newberry",
            "Cruel-Sea",
            "The Lion"
        ],
        // ],'first_name' => [
        //     'Tom',
        //     'Meryl',
        //     'Leonardo',
        //     'Scarlett',
        //     'Brad',
        //     'Angelina',
        //     'Denzel',
        //     'Emma',
        //     'Morgan',
        //     'Julia',
        //     'Robert',
        //     'Charlize',
        //     'Will',
        //     'Jennifer',
        //     'Johnny',
        //     'Nicole',
        //     'Matt',
        //     'Cate',
        //     'Samuel',
        //     'Natalie',
        //     'George',
        //     'Sandra',
        //     'Christian',
        //     'Anne',
        //     'Jake',
        //     'Kate',
        //     'Daniel',
        //     'Amy',
        //     'Ryan',
        //     'Helen',
        //     'Hugh',
        //     'Reese',
        //     'Mark',
        //     'Judi',
        //     'Tom',
        //     'Viola',
        //     'Chris',
        //     'Emily',
        //     'Bradley',
        //     'Emma',
        //     'Michael',
        //     'Gwyneth',
        //     'Colin',
        //     'Rachel',
        //     'John',
        //     'Cameron',
        //     'Liam',
        //     'Kirsten',
        //     'Keanu',
        //     'Diane',
        //     'Chris',
        //     'Angelica',
        //     'Jason',
        //     'Uma',
        //     'Anthony',
        //     'Meg',
        //     'Kevin',
        //     'Michelle',
        //     'Seth',
        //     'Jennifer',
        //     'Ewan',
        //     'Charlton',
        //     'Diane',
        //     'Chris',
        //     'Helen',
        //     'Gerard',
        //     'Jane',
        //     'Orlando',
        //     'Anne',
        //     'Seth',
        //     'Diane',
        //     'Daniel',
        //     'Jessica',
        //     'Owen',
        //     'Glenn',
        //     'Shia',
        //     'Isla',
        //     'Jamie',
        //     'Sienna',
        //     'Eddie',
        //     'Winona',
        //     'Patrick',
        //     'Zooey',
        //     'Ben',
        //     'Jodie',
        //     'Tom',
        //     'Catherine',
        //     'James',
        //     'Sarah',
        //     'Hugh',
        //     'Claire',
        //     'Aaron',
        //     'Naomi',
        //     'Joseph',
        //     'Salma',
        //     'Paul',
        //     'Laura',
        //     'Chris',
        //     'Jessica',
        //     'Jake',
        //     'Taylor',
        //     'Zayn',
        //     'Elton',
        //     'Pink',
        //     'David',
        //     'Lana',
        //     'The',
        //     'Jason',
        //     'Bon',
        //     'Michael',
        //     'Sam',
        //     'Enrique',
        //     'Metallica',
        //     'Christina',
        //     'Fleetwood',
        //     'Jennifer',
        //     'John',
        //     'Keith',
        //     'Luke',
        //     'One',
        //     'Pitbull',
        //     'Gwen',
        //     'Ozzy',
        //     'The',
        //     'Usher',
        //     'Shakira',
        //     'Ariana',
        //     'Miley',
        //     'Florence',
        //     'Mariah',
        //     'Shania',
        //     'Katy',
        //     'Stevie',
        //     'Blake',
        //     'Carrie',
        //     'The',
        //     'Niall',
        //     'Iggy',
        //     'Ariana',
        //     'Taylor',
        //     'Post',
        //     'Ed',
        //     'Bruno',
        //     'Zara',
        //     'Calvin',
        //     'Hozier',
        //     'Imagine',
        //     'The',
        //     'Nicki',
        //     'James',
        //     'Shawn',
        //     'Demi',
        //     'Justin',
        //     'OneRepublic',
        //     'Khalid',
        //     'Sam',
        //     'Drake',
        //     'Pink',
        //     'Lady',
        //     'Selena',
        //     'Coldplay',
        //     'Adele',
        //     'Beyoncé'
        // ],
        // 'second_name' => [
        //     'Hanks',
        //     'Streep',
        //     'DiCaprio',
        //     'Johansson',
        //     'Pitt',
        //     'Jolie',
        //     'Washington',
        //     'Stone',
        //     'Freeman',
        //     'Roberts',
        //     'De Niro',
        //     'Theron',
        //     'Smith',
        //     'Lawrence',
        //     'Depp',
        //     'Kidman',
        //     'Damon',
        //     'Blanchett',
        //     'Jackson',
        //     'Portman',
        //     'Clooney',
        //     'Bullock',
        //     'Bale',
        //     'Hathaway',
        //     'Gyllenhaal',
        //     'Winslet',
        //     'Day-Lewis',
        //     'Adams',
        //     'Gosling',
        //     'Mirren',
        //     'Jackman',
        //     'Witherspoon',
        //     'Wahlberg',
        //     'Dench',
        //     'Cruise',
        //     'Davis',
        //     'Hemsworth',
        //     'Blunt',
        //     'Cooper',
        //     'Watson',
        //     'Fassbender',
        //     'Paltrow',
        //     'Farrell',
        //     'McAdams',
        //     'Travolta',
        //     'Diaz',
        //     'Neeson',
        //     'Dunst',
        //     'Reeves',
        //     'Keaton',
        //     'Evans',
        //     'Huston',
        //     'Statham',
        //     'Thurman',
        //     'Hopkins',
        //     'Ryan',
        //     'Hart',
        //     'Pfeiffer',
        //     'Rogen',
        //     'Aniston',
        //     'McGregor',
        //     'Heston',
        //     'Kruger',
        //     'Pratt',
        //     'Hunt',
        //     'Butler',
        //     'Fonda',
        //     'Bloom',
        //     'Bancroft',
        //     'MacFarlane',
        //     'Lane',
        //     'Craig',
        //     'Chastain',
        //     'Wilson',
        //     'Close',
        //     'LaBeouf',
        //     'Fisher',
        //     'Foxx',
        //     'Miller',
        //     'Redmayne',
        //     'Ryder',
        //     'Stewart',
        //     'Deschanel',
        //     'Affleck',
        //     'Foster',
        //     'Hardy'],
    ];

    public function fantasyName($source)
    {
        $names = static::$fantasyNames[$source] ?? [];
        return $this->generator->randomElement($names);
    }
}
