name: Manual Sync to Notion

# Trigger the workflow manually via a button
on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type to sync (Issue/PR)'
        required: true
        default: 'Issue'
      title:
        description: 'Title of the event (Issue or PR)'
        required: true
        default: 'Sample Title'
      url:
        description: 'URL of the event'
        required: true
        default: 'https://github.com/yourrepo/sample'

jobs:
  sync_to_notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Sync to Notion
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        EVENT_TYPE="${{ github.event.inputs.event_type }}"
        TITLE="${{ github.event.inputs.title }}"
        URL="${{ github.event.inputs.url }}"

        # Sending data to Notion API
        curl -X POST https://api.notion.com/v1/pages \
        -H "Authorization: Bearer $NOTION_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Notion-Version: 2022-06-28" \
        -d '{
              "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" },
              "properties": {
                "Name": {
                  "title": [
                    {
                      "text": {
                        "content": "'"$TITLE"'"
                      }
                    }
                  ]
                },
                "URL": {
                  "url": "'"$URL"'"
                },
                "Event Type": {
                  "select": {
                    "name": "'"$EVENT_TYPE"'"
                  }
                }
              }
            }'
