name: Manual Sync to Notion

# Trigger the workflow manually via a button
on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event type to sync (Issue or PR)'
        required: true
        default: 'Issue'

jobs:
  sync_to_notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Event Data
      id: extract_data
      run: |
        EVENT_TYPE="${{ github.event.inputs.event_type }}"
        
        if [[ "$EVENT_TYPE" == "Issue" ]]; then
          TITLE="${{ github.event.issue.title }}"
          URL="${{ github.event.issue.html_url }}"
          DESCRIPTION="${{ github.event.issue.body }}"
          STATE="${{ github.event.issue.state }}"
        elif [[ "$EVENT_TYPE" == "PR" ]]; then
          TITLE="${{ github.event.pull_request.title }}"
          URL="${{ github.event.pull_request.html_url }}"
          DESCRIPTION="${{ github.event.pull_request.body }}"
          STATE="${{ github.event.pull_request.state }}"
        else
          echo "Invalid event type"
          exit 1
        fi

        echo "::set-output name=title::$TITLE"
        echo "::set-output name=url::$URL"
        echo "::set-output name=description::$DESCRIPTION"
        echo "::set-output name=state::$STATE"

    - name: Sync to Notion
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        TITLE="${{ steps.extract_data.outputs.title }}"
        URL="${{ steps.extract_data.outputs.url }}"
        DESCRIPTION="${{ steps.extract_data.outputs.description }}"
        STATE="${{ steps.extract_data.outputs.state }}"

        # Sending data to Notion API
        curl -X POST https://api.notion.com/v1/pages \
        -H "Authorization: Bearer $NOTION_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Notion-Version: 2022-06-28" \
        -d '{
              "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" },
              "properties": {
                "Name": {
                  "title": [
                    {
                      "text": {
                        "content": "'"$TITLE"'"
                      }
                    }
                  ]
                },
                "Description": {
                  "rich_text": [
                    {
                      "text": {
                        "content": "'"$DESCRIPTION"'"
                      }
                    }
                  ]
                },
                "URL": {
                  "url": "'"$URL"'"
                },
                "State": {
                  "select": {
                    "name": "'"$STATE"'"
                  }
                }
              }
            }'
