name: Sync to Notion

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  sync_to_notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send data to Notion
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        ISSUE_TITLE=${{ github.event.issue.title }}
        ISSUE_URL=${{ github.event.issue.html_url }}
        EVENT_TYPE="Issue"
        if [[ ${{ github.event_name }} == "pull_request" ]]; then
          ISSUE_TITLE=${{ github.event.pull_request.title }}
          ISSUE_URL=${{ github.event.pull_request.html_url }}
          EVENT_TYPE="Pull Request"
        fi

        curl -X POST https://api.notion.com/v1/pages \
        -H "Authorization: Bearer $NOTION_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Notion-Version: 2022-06-28" \
        -d '{
              "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" },
              "properties": {
                "Name": {
                  "title": [
                    {
                      "text": {
                        "content": "'"$ISSUE_TITLE"'"
                      }
                    }
                  ]
                },
                "URL": {
                  "url": "'"$ISSUE_URL"'"
                },
                "Event Type": {
                  "select": {
                    "name": "'"$EVENT_TYPE"'"
                  }
                }
              }
            }'
