name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure PHP 7.3
      uses: shivammathur/setup-php@v2
      env:
        runner: self-hosted
      with:
        php-version: '7.4'
        tools: composer, phpunit
        extensions: mbstring,PDO,grpc,tokenizer,xml,json,ctype,fileinfo,openssl,bcmath
    - uses: actions/checkout@v3
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: update composer
      run: composer self-update
    - name: Update composer
      run: composer update
    - name: Install dependencies
      run: composer install
    - name: Install Node Deps
      run: npm install
    - name: migrate db
      run: php artisan migrate --seed
    - name: start server
      run: php artisan serve

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
